### ISSUE TITLE
Locking is blocked during image cache update

### ISSUE THREAD

**Issue by ckudera** [jeffmhubbard/multilockscreen#12]
Fist of all, thank you for this great script.

When I change my monitor layout, I reload my I3 config, which triggers the multilockscreen image cache update (as recommended in #11 ). However, I can't lock my screen during the cache update (more specifically on "Rendering final wallpaper images..." and "Rendering final lockscreen images...").

Would it be possible to implement a functionality which enables the locking during the update just without an image?

**Comment by jeffmhubbard** [comment]
I just merged changes to fix this. There are no options, just a black screen with white text. Just the basics, so that the screen will always lock and be readable.

**Comment by ckudera** [comment]
Works great, thank you :)
