### ISSUE TITLE
Handling filenames containing escaped spaces

### ISSUE THREAD

**Issue by adamroyjones** [jeffmhubbard/multilockscreen#23]
Thanks for your work on extending betterlockscreen.

I had an issue running the following command:
```
multilockscreen -u /path/to/first/file -u /path/to/second/file --display 1
```
where the path to the second file contained spaces in the filename, but they were escaped (specifically, like `foo\ bar\ baz.jpg`, with no quotation marks surrounding the argument). The command hung when attempting to resize the second image. Renaming the file to remove the spaces fixed the issue. Do you know if you can reproduce this?

**Comment by jeffmhubbard** [comment]
Can you try the latest commit and see if that resolves the issue?

**Comment by adamroyjones** [comment]
It does! Thanks for looking into it.
