### ISSUE TITLE
Lock on suspend not working correctly

### ISSUE THREAD

**Issue by minhduc0711** [jeffmhubbard/multilockscreen#28]
Hi, I'm running this command from the README
```
xss-lock -l -- multilockscreen --lock blur &
```
When I suspend my machine, for some reason the lock screen would show up first, and the machine only suspends after I type in my password. Any idea about what might have gone wrong here?

Thanks in advance!

**Comment by jeffmhubbard** [comment]
How are you suspending your system?

I'm guessing you are trying to use the `-s` argument. With `xss-lock` you should call `systemctl suspend` from a terminal or menu directly. I should clarify that in the README.

**Comment by minhduc0711** [comment]
@jeffmhubbard I used `systemctl suspend` actually.
Update: When I removed `~/.cache/multilock`, it seems to work correctly for some reason.

**Comment by jeffmhubbard** [comment]
@minhduc0711 That's strange... I can't reproduce this any way other than what I mentioned before. The cache directory only contains images, so I'm not sure how that fixed it.

Closing for now. You can reopen if it starts happening again.

**Comment by minhduc0711** [comment]
@jeffmhubbard yeah but then I would only have a black background. I'll try digging deeper to see why the failsafe lock makes it work again.

**Comment by jeffmhubbard** [comment]
Try commenting out line 705
```
[[ $runsuspend ]] || lockargs+=(-n)
```
This will allow `i3lock` to fork. The failsafe doesn't pass `-n` to `i3lock`, that's probably why it's working.

**Comment by minhduc0711** [comment]
@jeffmhubbard yup that's the culprit in my case. Much appreciated for the help!
