### ISSUE TITLE
Lock and Suspend

### ISSUE THREAD

**Issue by ppublicgit** [jeffmhubbard/multilockscreen#29]
First off I want to say I enjoy this fork. It easily fixed my two screen setup to properly display the lock screen image. I was just wondering if there is there a way to lock and suspend? In betterlockscreen, you just pass -s to suspend. Then when the computer is used again you have to log back in. On this, I have not been able to find this feature. I saw that you can use systemctl suspend, but this does not lock the screen, so anybody who walks up to the computer and ends the suspension would have full access to the computer. I tried:

multilockscreen -l; systemctl suspend

But that just locked the screen and waited until I logged back in to suspend the screen.

**Comment by jeffmhubbard** [comment]
@ppublicgit  I recommend using `xss-lock`, as it handles locking for idle timeout and suspend.

I did keep the `-s` argument and systemd file from `betterlockscreen`, but it was left undocumented to discourage use. But I see now it is not working correctly, so I'll push a fix for that soon.

**Comment by ppublicgit** [comment]
Okay, thanks. I am not sure I am fully understanding the benefit of xss-lock vs. -s. I will try and use xss-lock and see how it works. I am closing this issue.
