### ISSUE TITLE
Specify minimum version for i3lock-color

### ISSUE THREAD

**Issue by MatteoJoliveau** [jeffmhubbard/multilockscreen#33]
Hello! Been using this awesome script for a couple of years now, and today I'm migrating from Arch Linux to NixOS. There, I realized that i3color-lock version 2.12.c (available in NixOS stable repos) is not compatible with multilockscreen, because it lacks the `--pass-screen-key` flags. We actually need 2.12.c.5 (as provided in the Arch package and thankfully available in NixOS unstable repo).

It took me a while to figure out the issue, so I think it could be worth to document it in the README or elsewhere. I can provide a quick PR if you'd like.

**Comment by jeffmhubbard** [comment]
Yes, please submit a PR. Also, it would be awesome for have install instructions for other distros, feel free to add NixOS while you're at it.
