### ISSUE TITLE
Unexpected error while running multilockscreen

### ISSUE THREAD

**Issue by epixinvites** [jeffmhubbard/multilockscreen#39]
`multilockscreen --lock`

Returns me:
```
skynet@debian:~$ multilockscreen --lock
[m] multilockscreen
[*] Running prelock...
[*] Locking screen...
i3lock: unrecognized option '--screen'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-I timeout] [-f]
[*] Running postlock...
```
i3lock version is `i3lock: version 2.13 © 2010 Michael Stapelberg`

**Comment by jeffmhubbard** [comment]
It looks like you are running stock `i3lock`. We require `i3lock-color`, which probably isn't in the Debian repos. You can find instructions [here](https://github.com/Raymo111/i3lock-color#debian) for building `i3lock-color` from source.

**Comment by epixinvites** [comment]
Ah yes it worked, thanks a lot.

**Comment by jeffmhubbard** [comment]
Glad to hear you got it working
