### ISSUE TITLE
Multiscreen not working properly

### ISSUE THREAD

**Issue by gvolpe** [jeffmhubbard/multilockscreen#42]
I have my laptop's display + an external monitor and this is what I see when running `multilockscreen -l dim`

![bug](https://i.imgur.com/SzYaQnG.jpg)

This is what `xrandr` shows.

```
$ xrandr --listactivemonitors
Monitors: 2
 0: +*HDMI-A-0 3840/700x2160/390+0+0  HDMI-A-0
 1: +eDP 1920/344x1080/194+0+0  eDP
```

It seems both resolutions are displayed at the same time. On my laptop's screen it is shown properly but not on the external monitor, which is the one I use the most. 

The clock's box is also placed incorrectly but that's a problem for a different day :smile: 

Any ideas on how to get this working properly?

**Comment by jeffmhubbard** [comment]
`xrandr` is showing that both monitors are positioned at `+0+0` so they are overlapped. Technically, `multilockscreen` is functioning correctly. Try something like `xrandr --output HDMI-A-0 --pos 1920x0` to position them side by side.

The other issue you're seeing is related to your HiDPI display. See #7.

**Comment by gvolpe** [comment]
Thanks for the quick response @jeffmhubbard ! Unfortunately, that didn't work, only half of the lock screen is shown in my main display.

Thanks for linking the issue, I'll have a look :+1:

**Comment by jeffmhubbard** [comment]
@gvolpe  You will need to adjust the `--pos` value (probably 3840) according to your setup, if they are still overlapping.

`i3lock` only accepts one image, so we have to peice together two images and make one large image that spans across both displays. We get the total screen dimensions from `xrandr`. If they overlap, then the total width is less than width1+width2. So they resulting image is too small.

**Comment by gvolpe** [comment]
@jeffmhubbard thanks for helping out. I'll make sure to try different configurations and report back.

**Comment by gvolpe** [comment]
Got it working by adjusting the display layout as suggested. Here's what I ended up with.

![layout](https://i.imgur.com/pJKV5S3.png)

And my XRandr config, in case it helps someone else.

```nix
{
    xrandrHeads = [
      { output = "HDMI-A-0";
        primary = true;
        monitorConfig = ''
          Modeline "3840x2160_30.00"  338.75  3840 4080 4488 5136  2160 2163 2168 2200 -hsync +vsync
          Option "PreferredMode" "3840x2160_30.00"
          Option "Position" "0 0"
        '';
      }
      { output = "eDP";
        monitorConfig = ''
          Option "PreferredMode" "1920x1080"
          Option "Position" "3840 0"
        '';
      }
    ];
}
```

Thanks a lot for your kind help @jeffmhubbard !

**Comment by gvolpe** [comment]
Unfortunately, this layout configuration screws up how my WM workspaces operate. I'm used to working on a single display.

Is there a way to tell `multiscreen` to show the right resolution only for the primary display? I don't care if it's broken in the other display (the laptop's one) because I don't use it when the HDMI display is connected.
