### ISSUE TITLE
White flashing before image shows

### ISSUE THREAD

**Issue by CatoMaior** [jeffmhubbard/multilockscreen#43]
I have noticed that when I lock my screen, before the cached image loads, there is a sort of white flash. The same thing happens when I resume after a suspend. It's not a real problem, but having a dark theme in everything all that light is pretty annoying

**Comment by jeffmhubbard** [comment]
This is because `i3lock`'s default color is white. You shouldn't see this _under normal circumstances_, so there may be some underlying issue that is causing `i3lock` to take longer to display the image.

That being said, just in case, we can set `i3lock --color`. Can you test #44? You'll have to add `bgcolor=000000` to your config file.

**Comment by jeffmhubbard** [comment]
@CatoMaior

**Comment by CatoMaior** [comment]
> This is because `i3lock`'s default color is white. You shouldn't see this _under normal circumstances_, so there may be some underlying issue that is causing `i3lock` to take longer to display the image.
> 
> That being said, just in case, we can set `i3lock --color`. Can you test #44? You'll have to add `bgcolor=000000` to your config file.

It worked, thanks!

**Comment by CatoMaior** [comment]
I am now facing a similar issue only when resuming from suspend. But this time instead of the white flashing I see the my i3 session and it looks like it does not load the black background set with `bg-color=000000`

**Comment by jeffmhubbard** [comment]
@CatoMaior This sounds like a different issue. What you describe sounds like i3lock isn't actually locking until you're trying to wake up from suspend. How exactly are you suspending the system (close lid, systemctl suspend, etc)?  And are you using the systemd service?

**Comment by CatoMaior** [comment]
I have `xss-lock -- multilockscreen -l` in my startup script and I suspend with `systemctl suspend`. And I am using systemd service

**Comment by jeffmhubbard** [comment]
You shouldn't be using both xss-lock and the systemd service. That may be part of the problem.
