### ISSUE TITLE
Prelock & Postlock Scoped Variables

### ISSUE THREAD

**Issue by medoix** [jeffmhubbard/multilockscreen#48]
Hello, i was attempting to use the example prelock and postlock functions in the example config but quickly noticed that notify-send was not showing. After some trial and error it seems to me that it is because the start_time variable is not available in the postlock function in order to calculate the time difference. I can only get it to work if i define the start_time variable in the postlock function but then that means i don't actually have the proper start time of the lock.

Am i missing something or is this possibly a bug?

**Comment by jeffmhubbard** [comment]
No, it probably never worked. It was just an idea I had for the example file, so I probably didn't test it well. It will fixed or removed following the merge. If you have a solution, you can open a PR against betterlockscreen multi-monitor branch.
