### ISSUE TITLE
Resuming dunst notifications even if they were already turned off before locking.

### ISSUE THREAD

**Issue by GaetanLepage** [jeffmhubbard/multilockscreen#52]
This is an issue I first submitted on the betterlockscreen git but it is also relevant for this problem.
[original issue](https://github.com/pavanjadhaw/betterlockscreen/issues/219)

------------------
It is a great feature that multilockscreen blocks dunst notifications during lock time and enables them back at unlock.
However, in the event were the user would have turned of the notifications for some other reason manually, they will be turned back on by multilockscreen.

One would then have to turn them back off each time he unlocks his screen.
dunstctl is-paused could be used to test if the notifications were blocked initially. multilockscreen should then do nothing with dunst.

I admit that this is an edge case that might not be worth tackling.
The fix would need to keep an internal state between lock and unlock: were_dunst_notifications_already_turned_off_before_locking. The latter variable, if true would prevent turning notifications back on in postlock.

If you think that this is relevant, I could work on a PR to do it.
If you prefer your tool to stay simple and ignore this edge case, I would completely get it.

Thank you for the nice work anyway !

**Comment by jeffmhubbard** [comment]
@GaetanLepage 
Please make a PR for the multi-monitor branch of betterlockscreen.

**Comment by GaetanLepage** [comment]
I think it has been fixed by https://github.com/pavanjadhaw/betterlockscreen/pull/233.
Is it fine for you ?
